name: gtrepo
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
      
      
  workflow_dispatch:



jobs:
  cli:
    name: makeDescription
    runs-on: ubuntu-latest
    permissions:
     checks: write
     contents: write
     
    steps:
     
    - name: Git checkout
      uses: actions/checkout@v3

     # Create Directories

    - name: create directories
      run: |
        mkdir frak
        mkdir ant
        mkdir fontmix
        mkdir frak/frak_simple
        mkdir frak/frak_complex
        mkdir ant/ant_simple
        mkdir ant/ant_complex
        mkdir fontmix/fontmix_simple
        mkdir fontmix/fontmix_complex


     # Clone Repos
    - name: clone repos and delete files
      run: |
        cd frak
        cd frak_simple
        git clone https://github.com/tboenig/16_frak_simple.git --branch gh-pages
        cd 16_frak_simple
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ..
        git clone https://github.com/tboenig/17_frak_simple.git --branch gh-pages
        cd 17_frak_simple
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ..
        git clone https://github.com/tboenig/18_frak_simple.git --branch gh-pages
        cd 18_frak_simple
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ..
        git clone https://github.com/tboenig/19_frak_simple.git --branch gh-pages
        cd 19_frak_simple
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ../..
        
        cd frak_complex
        git clone https://github.com/tboenig/16_frak_complex.git --branch gh-pages
        cd 16_frak_complex
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ..
        git clone https://github.com/tboenig/17_frak_complex.git --branch gh-pages
        cd 17_frak_complex
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ..
        git clone https://github.com/tboenig/18_frak_complex.git --branch gh-pages
        cd 18_frak_complex
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ../../..
        
        cd ant
        cd ant_simple
        git clone https://github.com/tboenig/16_ant_simple.git --branch gh-pages
        cd 16_ant_simple
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ..
        git clone https://github.com/tboenig/18_ant_simple.git --branch gh-pages
        cd 18_ant_simple
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ../..
        
        cd ant_complex
        git clone https://github.com/tboenig/16_ant_complex.git --branch gh-pages
        cd 16_ant_complex
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ..
        git clone https://github.com/tboenig/19_ant_simple.git --branch gh-pages
        cd 19_ant_simple
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ../../..
        
        cd fontmix
        cd fontmix_simple
        git clone https://github.com/tboenig/17_fontmix_simple.git --branch gh-pages
        cd 17_fontmix_simple
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ../..
        
        cd fontmix_complex
        git clone https://github.com/tboenig/18_fontmix_complex.git --branch gh-pages
        cd 18_fontmix_complex
        rm -rf _config.yml index.md metadata.md overview.md table.md table_hide.css
        cd ../../..
        ls -l

     
     
     
     
     
     # Installation Styles
      
    #- name: clone repos
    #  run: | 
    #    git clone https://github.com/tboenig/gt-repo-scripts.git
    #    mv gt-repo-scripts/scripts scripts/
    #    rm -r gt-repo-scripts

          
    # Installation and Directories
      
    
          
    #- name: Download and install saxon
    #  run: |
    #    wget https://sourceforge.net/projects/saxon/files/Saxon-HE/10/Java/SaxonHE10-5J.zip/download 
    #    unzip download
                      
    #- name: make ocrdzip_out
    #  run: mkdir ocrdzip_out
      
    #- name: make gh-pages_out
    #  run: mkdir ghout
      
    #- name: make readme_out 
    #  run:  sh scripts/readmefolder.sh


    #- name: readme.xml file
    #  run: sh scripts/xreadme.sh  

          
    
   # Transformation and analyzing
    
              
    #- name: transform METADATA and make GT-Overview
    #  run: |
    #    java -jar saxon-he-10.5.jar -xsl:scripts/gt-overview_metadata.xsl \
    #    output=METADATA repoBase=$GITHUB_REF_NAME repoName=$GITHUB_REPOSITORY bagitDumpNum=$GITHUB_RUN_NUMBER releaseTag=$GITHUB_REF_NAME \
    #    -s:scripts/gt-overview_metadata.xsl -o:ghout/metadata.md
    #  shell: bash

    
      
      
    #- name: generate README
    #  run: |
    #    java -jar saxon-he-10.5.jar -xsl:scripts/gt-overview_metadata.xsl \
    #    output=README repoBase=$GITHUB_REF_Name repoName=$GITHUB_REPOSITORY \
    #    -s:scripts/gt-overview_metadata.xsl -o:README.md
    #  shell: bash
      
    
  
    #- name: Index-link
    #  run: |
    #     cd ghout
    #     ln -s metadata.md index.md

         
   

    #- name: archive the ocrdzip files from ocrdzip_out folder
    #  uses: thedoctor0/zip-release@master
    #  with:
    #     filename: bagitDump-v${{ github.run_number }}.zip
    #     path: 'ocrdzip_out'
      
        
    #- name: Upload Release
    #  uses: ncipollo/release-action@v1
    #  with:
    #      artifacts: './bagitDump-v*.zip'
    #      artifactContentType: application/zip
    #      name: Release ${{ github.run_number }}_${{ github.ref_name }}
    #      body: |
    #        <dl>
    #        <dt>Version:</dt> 
    #        <dd>${{ github.ref_name }}</dd>
    #        <dt>Info:</dt>
    #        <dd>To use the Ground Truth download the bagitDump-v${{ github.run_number }}.zip file.<br/>
    #        The zip file contains all ocr-d-bagit files.<br/>
    #        The Metadata.json file contains metadata for the Ground Truth corpus.<br/>
    #        The Mets.xml file lists all containing documents/bagits.<br/>
    #        The bagits correspond to the <a href="https://ocr-d.de/de/spec/ocrd_zip.html">OCR-D Bagit Spec</a>.</dd>
    #        </dl>
    #      token: ${{ secrets.GITHUB_TOKEN }}
          
    #- name: Commit README
    #  run: |
    #    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #    git config --local user.name "github-actions[bot]"
    #    git add README.md
    #    git commit -m "[Automatic] Update readme files" || echo "Nothing to update"
    #    git push origin HEAD:main


    #- name: Deploy GT-Overview to GitHub Pages 🚀
    #  uses: JamesIves/github-pages-deploy-action@v4.4.1
    #  with:
    #      branch: gh-pages # The branch the action should deploy to.
    #      folder: ghout  # The folder the action should deploy.
